spring:
  application:
    name: eureka-client
#  security: #登录所需的账号密码
#    user:
#      name: user
#      password: user

server:
  port: 8033

eureka:
  instance:
    hostname: 192.168.2.221
    lease-expiration-duration-in-seconds: 2 # 2秒即过期
    lease-renewal-interval-in-seconds: 1 # 1秒一次心跳
    client:
      service-url:
        defaultZone: http://192.168.2.44:1000/eureka/
    healthcheck:
      enabled: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
