server:
  port: 8033

spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  boot:
    admin:
      client:
        # url: http://localhost:8036 # 针对非cloud使用ip地址
        instance:
          service-base-url: http://admin-monitor-server
        username: admin
        password: 123456
#  main:
#    allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: 192.168.2.221
    lease-expiration-duration-in-seconds: 2 # 2秒即过期
    lease-renewal-interval-in-seconds: 1 # 1秒一次心跳
  client:
    service-url:
      defaultZone: http://user:user@192.168.2.221:8032/eureka/

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 500
  ReadTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
turbine:
  app-config: eureka-client #注册中心的调用者名称
  aggregator:
    cluster-config: default # 默认
  cluster-name-expression: new String("default")
  combine-host-port: true
