server:
  port: 8033

spring:
  application:
    name: eureka-client
  profiles:
    application:
      name: eureka-client
  security:
    user:
      name: user
      password: user
eureka:
  instance:
    hostname: 192.168.2.221
    lease-expiration-duration-in-seconds: 2 # 2秒即过期
    lease-renewal-interval-in-seconds: 1 # 1秒一次心跳
  client:
    service-url:
      defaultZone: http://user:user@192.168.2.221:8032/eureka/
      security:
        basic: user
        passowrd: user
