server:
  port: 8034

spring:
  application:
    name: eureka-provider
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2 #指定数据源类型
#    url: jdbc:h2:mem:cloud # 内存数据库
#    driver-class-name: org.h2.Driver
    # mysql数据库
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wanzhs
    password: 123456
    schema: classpath:/sql/schema.sql   # 指定h2数据库的建表脚本
    data: classpath:/sql/data.sql       # 指定h2数据库的数据脚本
    initialization-mode: always
  h2:
    console:
      path: /h2-console
      enabled: true
  boot:
    admin:
      client:
        instance:
          service-base-url: http://admin-monitor-server
        username: admin
        password: 123456
  #  main:
#    allow-bean-definition-overriding: true
  cloud:
    refresh:
      refreshable: none
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  instance:
    hostname: 192.168.2.221
    lease-expiration-duration-in-seconds: 2 # 2秒即过期
    lease-renewal-interval-in-seconds: 1 # 1秒一次心跳
  client:
    service-url:
      defaultZone: http://user:user@192.168.2.221:8032/eureka/
logging:
  level:
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
info:
  app:
    name: microservice-simple-provider-user
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env