server:
  port: 8035

spring:
  application:
    name: oauth2-center
eureka:
  instance:
    hostname: 192.168.2.221
    lease-expiration-duration-in-seconds: 2 # 2秒即过期
    lease-renewal-interval-in-seconds: 1 # 1秒一次心跳
  client:
    service-url:
      defaultZone: http://user:user@192.168.2.221:8032/eureka/

