server:
  port: 8032

spring:
  application:
    name: eureka-server
  security:
    user:
      name: user
      password: user
  boot:
    admin:
      client:
        instance:
          service-base-url: http://admin-monitor-server
        username: admin
        password: 123456
eureka:
  instance:
    hostname: 192.168.2.221
    ip-address: 192.168.2.221
    prefer-ip-address: true
  client:
    fetch-registry: true  # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    register-with-eureka: true # 由于该应用为注册中心，所以设置为false，代表不想注册中心注册自己
    service-url:
      defaultZone: http://user:user@${eureka.instance.hostname}:${server.port}/eureka/
    # 配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    ## 关闭自我保护
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false
    #     清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 5000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env