
server:
  port: 8038

spring:
  application:
    name: oauth2-jwt
  security:
    user:
      name: root
      password: 1234
eureka:
  instance:
    hostname: 192.168.2.221
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://user:user@192.168.2.221:8032/eureka/
